# Generated by Django 5.0.5 on 2024-05-23 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='autor',
        ),
        migrations.AlterField(
            model_name='livro',
            name='foto_capa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.foto'),
        ),
    ]
