# Generated by Django 5.0.5 on 2024-05-23 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_livro_autor_alter_livro_foto_capa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='livros',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='status',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='livro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emprestimoLivro', to='app.livro'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('APROVADO', 'Aprovado'), ('PENDENTE', 'Pendente'), ('CANCELADO', 'Cancelado')], max_length=10),
        ),
        migrations.DeleteModel(
            name='EmprestimoLivro',
        ),
    ]
