# Generated by Django 5.0.5 on 2024-05-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_autor_remove_emprestimo_livros_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='foto_capa',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Foto',
        ),
    ]
